version: '2'
services: 
  microservice:
    build: "./"
    image: cloudnativego:1.0.2-alpine
    environment: 
    - PORT=9090
    ports:
    - "9090:9090"
  nginx:
    image: "nginx:1.14.2"
    ports: 
    - "8080:80"
    links: 
    - microservice