apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name:  cloudnativego
  labels:
    name:  cloudnativego
spec:
  replicas: 2
  revisionHistoryLimit: 10
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  template:
    metadata:
      labels: 
        app:  cloudnativego
        tier:  service
    spec:
      containers:
      - name:  cloudnativego
        image:  "jaynejacobs/cloudnativego:1.0.2-alpine"
        resources:
          requests:
            memory: "64Mi"
            cpu: "125m"
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 5       
        env:
        - name: PORT
          value: "8080"